---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
    checks:
      Insecure Source:
        enabled: false
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.coffee"
  - "**.inc"
  - "**.js"
exclude_paths:
- spec/
- vendor/
- config/environments/
