image: docker

services:
  - postgres:9.4.1

variables:
  POSTGRES_DB: screensmart_test
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""
  DATABASE_URL: "postgres://runner@postgres:5432/screensmart_test"
  MYSQL_ROOT_PASSWORD: "secret"
  SIMPLECOV: "true"

stages:
  - docker
  - test

cache:
  paths:
    - gems

before_script:
  - docker login registry.roqua.nl -u "$REGISTRY_USERNAME" -p "$REGISTRY_PASSWORD"

docker:
  stage: docker
  retry: 2
  script:
    - docker build . --pull -t registry.roqua.nl/roqua/screensmart
    - id=$(docker create registry.roqua.nl/roqua/screensmart)
    - rm -Rf $CI_PROJECT_DIR/gems
    - docker cp $id:/gems $CI_PROJECT_DIR/gems
    - docker rm -v $id
    - docker push registry.roqua.nl/roqua/screensmart

rubocop:
  stage: test
  dependencies:
    - docker
  script:
    - docker pull registry.roqua.nl/roqua/screensmart
    - docker run -t registry.roqua.nl/roqua/screensmart bundle exec rubocop -D

# rspec:
#   script:
#     - rm config/database.yml
#     - bundle exec rake db:create db:schema:load
#     - bundle exec rspec
#   artifacts:
#     when: always
#     name: "screenshots-$CI_COMMIT_SHA"
#     expire_in: 3d
#     paths:
#       - coverage/
#       - tmp/capybara
