image: registry.roqua.nl/roqua/rq

before_script:
  - docker login registry.roqua.nl -u "$REGISTRY_USERNAME" -p "$REGISTRY_PASSWORD"

docker:
  retry: 2
  script:
    - rq build
    - rq run bundle exec rake db:create
    - rq run bin/rails db:environment:set RAILS_ENV=test
    - rq run bundle exec rake db:schema:load
    - rq run bundle exec rspec
    - rq run bundle exec rubocop -D
    - rq push

dependency_scanning:
  image: registry.roqua.nl/roqua/roqua-build-images:dependency-scanning
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:stable-dind
  script:
    - scan_dependencies.sh
  artifacts:
    paths: [gl-dependency-scanning-report.json]
