image: registry.roqua.nl/roqua/rq

before_script:
  - docker login registry.roqua.nl -u "$REGISTRY_USERNAME" -p "$REGISTRY_PASSWORD"

docker:
  retry: 2
  script:
    - rq build
    - rq deploy screensmart test --tag $CI_COMMIT_SHA --database postgresql --stages prepare
    - rq run bundle exec rspec
    - rq run bundle exec rubocop -D
    - rq push
