image: registry.roqua.nl/roqua/rq

before_script:
  - docker login registry.roqua.nl -u "$REGISTRY_USERNAME" -p "$REGISTRY_PASSWORD"

docker:
  retry: 2
  script:
    - rq build
    - rq run bundle exec rake db:create
    - rq run bin/rails db:environment:set RAILS_ENV=test
    - rq run bundle exec rake db:schema:load
    - rq run bundle exec rspec
    - rq run bundle exec rubocop -D
    - rq push

dependency_scanning:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:stable-dind
  script:
    - apk add --no-cache alpine-sdk ruby ruby-dev
    - gem install json --no-ri --no-rdoc
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env DEP_SCAN_DISABLE_REMOTE_CHECKS="${DEP_SCAN_DISABLE_REMOTE_CHECKS:-false}"
        --volume "$PWD:/code"
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/dependency-scanning:$SP_VERSION" /code
    - echo gl-dependency-scanning-report.json | ruby -e "require 'json'; raise('One or more vulnerabilities found') if JSON.load(STDIN.read).any?" 
  artifacts:
    paths: [gl-dependency-scanning-report.json]
