image: registry.roqua.nl/roqua/rq

services:
  - postgres:9.4

variables:
  DATABASE_URL: "postgres://runner@postgres:5432/screensmart_test"

before_script:
  - docker login registry.roqua.nl -u "$REGISTRY_USERNAME" -p "$REGISTRY_PASSWORD"

docker:
  retry: 2
  script:
    - rq build
    - rq run bundle exec rspec
    - rq run bundle exec rubocop -D
    - rq push
