image: registry.roqua.nl/roqua/rq

before_script:
  - docker login registry.roqua.nl -u "$REGISTRY_USERNAME" -p "$REGISTRY_PASSWORD"

docker:
  retry: 2
  script:
    - rq build
    - rq test shell bundle exec rake db:create
    - rq test shell bin/rails db:environment:set RAILS_ENV=test
    - rq test shell bundle exec rake db:schema:load
    - rq test shell bundle exec rspec
    - rq teardown
    - sed -i 's/postgres:9.4/postgres:10/g' infrastructure.yml
    - rq test shell bundle exec rake db:create
    - rq test shell bin/rails db:environment:set RAILS_ENV=test
    - rq test shell bundle exec rake db:schema:load
    - rq test shell bundle exec rspec    
    - rq test shell bundle exec rubocop -D
    - rq push

dependency_scanning:
  image: registry.roqua.nl/roqua/dependency_scanning
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:stable-dind
  script:
    - scan_dependencies.sh
  artifacts:
    paths: [gl-dependency-scanning-report.json]

sast:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SAST_CONFIDENCE_LEVEL="${SAST_CONFIDENCE_LEVEL:-3}"
        --volume "$PWD:/code"
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/sast:$SP_VERSION" /app/bin/run /code
  artifacts:
    paths: [gl-sast-report.json]