image: "roqua/roqua-build-images:ruby-2.3.3-phantomjs-2.1.1-bundler-gemnasium"

services:
  - postgres:9.4

variables:
  POSTGRES_DB: screensmart_test
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""
  DATABASE_URL: "postgres://runner@postgres:5432/screensmart_test"
  MYSQL_ROOT_PASSWORD: "secret"
  SIMPLECOV: "true"

before_script:
  - ruby -v
  - bundle-cache

stages:
  - test
  - post-test

rubocop:
  stage: test
  script:
  - bundle exec rubocop

rspec:
  stage: test
  script:
  - rm config/database.yml
  - bundle exec rake db:create db:schema:load
  - bundle exec rspec
  artifacts:
    when: always
    name: "screenshots-$CI_COMMIT_SHA"
    expire_in: 3d
    paths:
      - coverage/
      - tmp/capybara

pages:
  stage: post-test
  dependencies:
    - rspec
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
