image: registry.roqua.nl/roqua/roqua-build-images:ruby-2.3-rails-base-test

services:
  - postgres:9.4.1

variables:
  POSTGRES_DB: screensmart_test
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""
  DATABASE_URL: "postgres://runner@postgres:5432/screensmart_test"
  MYSQL_ROOT_PASSWORD: "secret"
  SIMPLECOV: "true"

cache:
  paths:
    - .gems

before_script:
  - ruby -v
  - bundle-cache

docker:
  image: docker
  before_script:
    - docker login registry.roqua.nl -u "$REGISTRY_USERNAME" -p "$REGISTRY_PASSWORD"
  script:
    - docker build . -t registry.roqua.nl/roqua/screensmart
    - id=$(docker create registry.roqua.nl/roqua/screensmart)
    - rm -Rf .gems
    - docker cp $id:/app/.gems - > .gems
    - docker rm -v $id
    - docker push registry.roqua.nl/roqua/screensmart

rubocop:
  script:
    - bundle exec rubocop

rspec:
  script:
    - rm config/database.yml
    - bundle exec rake db:create db:schema:load
    - bundle exec rspec
  artifacts:
    when: always
    name: "screenshots-$CI_COMMIT_SHA"
    expire_in: 3d
    paths:
      - coverage/
      - tmp/capybara
