AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    # Exclude generated or external code
    - bin/**/*
    - vendor/**/*
    - db/schema.rb

Metrics/LineLength:
  Max: 120

Metrics/ModuleLength:
  Exclude:
    # Temporarily contains functionality that belongs to screensmart-r
    - app/models/r_package.rb

# Trust developers to document where neccesary, otherwise
# rely on the code being self-documenting
Style/Documentation:
  Enabled: false

Style/LambdaCall:
  Exclude:
    - Guardfile

Metrics/MethodLength:
  Exclude:
    - spec/**/*_spec.rb
    - app/pdfs/response_report.rb
