inherit_from:
  - styleguide/ruby/rubocop-rails-5.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    # Exclude generated or external code
    - bin/**/*
    - vendor/**/*
    - db/schema.rb

# The project has models without ActiveRecord where this is a false positive
Rails/DynamicFindBy:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/environments/**/*.rb
    - Guardfile
    - lib/tasks/export.rake
    - spec/**/*.rb

Metrics/ModuleLength:
  Exclude:
    # Temporarily contains functionality that belongs to screensmart-r
    - app/models/r_package.rb

Metrics/MethodLength:
  Exclude:
    - spec/**/*_spec.rb
    - spec/support/mock_all_calls_to_r.rb
    - app/pdfs/response_report.rb

Metrics/AbcSize:
  Exclude:
    - app/pdfs/response_report.rb
    - app/controllers/responses_controller.rb
    - spec/support/mock_all_calls_to_r.rb

Layout/EmptyLineAfterGuardClause:
  Enabled: false

# Trust developers to document where neccesary, otherwise
# rely on the code being self-documenting
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/LambdaCall:
  Exclude:
    - Guardfile
