AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    # Exclude generated or external code
    - bin/**/*
    - vendor/**/*
    - db/schema.rb

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - config/environments/**/*.rb
    - Guardfile

Metrics/ModuleLength:
  Exclude:
    # Temporarily contains functionality that belongs to screensmart-r
    - app/models/r_package.rb

Metrics/MethodLength:
  Exclude:
    - spec/**/*_spec.rb
    - spec/support/mock_all_calls_to_r.rb
    - app/pdfs/response_report.rb

Metrics/AbcSize:
  Exclude:
    - app/pdfs/response_report.rb

# Trust developers to document where neccesary, otherwise
# rely on the code being self-documenting
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/LambdaCall:
  Exclude:
    - Guardfile

# Too subjective
Style/PercentLiteralDelimiters:
  Enabled: false

Style/SymbolArray:
  Enabled: false
