AllCops:
  Exclude:
    # Exclude generated code
    - bin/**/*
    - spec/teaspoon_env.rb
    - vendor/**/*

Metrics/LineLength:
  Max: 120

# Trust developers to document where neccesary, otherwise
# rely on the code being self-documenting
Style/Documentation:
  Enabled: false

Style/LambdaCall:
  Exclude:
    - Guardfile

Metrics/MethodLength:
  Exclude:
    - spec/**/*_spec.rb
