default: &defaults
  push_api_key: "<%= ENV['APPSIGNAL_PUSH_API_KEY'] %>"
  name: "Screensmart"
  slow_request_threshold: 200
  enable_frontend_error_catching: true

development:
  <<: *defaults
  active: false

test:
  <<: *defaults
  active: false

production:
  <<: *defaults
  active: true
