default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: screensmart_development

test:
  <<: *default
  database: screensmart_test

staging: &staging
  <<: *default

production:
  <<: *default
